language: python
sudo: required
services: docker

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - g++-4.9

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99

env:
    matrix:
        - CMD='test/setup.py default_tcp; ./.travis_make_ssh_key.sh; mm-delay 5 sh -c ''ssh -o \"StrictHostKeyChecking=no\" $USER@\$MAHIMAHI_BASE exit; mm-delay 5 test/test.py default_tcp -r $USER@\$MAHIMAHI_BASE:pantheon -t 10'' '
        #- CMD='test/setup.py quic        &&  test/test.py -f 2 -t 10 quic'
        #- CMD='test/setup.py webrtc      &&  test/test.py -f 2 -t 10 webrtc'
        #- CMD='test/setup.py default_tcp &&  test/test.py -f 2 -t 10 default_tcp'
        #- CMD='test/setup.py vegas       &&  test/test.py -f 2 -t 10 vegas'
        - CMD='test/setup.py koho_cc     &&  test/test.py -f 2 -t 10 koho_cc'
        #- CMD='test/setup.py ledbat      &&  test/test.py -f 2 -t 10 ledbat'
        #- CMD='test/setup.py pcc         &&  test/test.py -f 2 -t 10 pcc'
        #- CMD='test/setup.py verus       &&  test/test.py -f 2 -t 10 verus'
        #- CMD='test/setup.py scream      &&  test/test.py -f 2 -t 10 scream'
        #- CMD='test/setup.py sprout      &&  test/test.py -f 2 -t 10 sprout'
        #- CMD='test/setup.py taova       &&  test/test.py -f 2 -t 10 taova'

script:
  - test/pre_setup.py
  - eval $CMD

notifications:
  slack: keithw:WjjCMz8yip3iQrHKBmkFGI1u
  email: false
